# Generated by Django 3.1.3 on 2020-11-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkUserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkUserOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('работа', 'Work'), ('школа', 'School'), ('университет', 'University')], max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkUserPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langs', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('inspired_by', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking', models.CharField(blank=True, choices=[(1, 'Резко негативное'), (2, 'Негативное'), (3, 'Компромиссное'), (4, 'Нейтральное'), (5, 'Положительное')], max_length=255, null=True)),
                ('alcohol', models.CharField(blank=True, choices=[(1, 'Резко негативное'), (2, 'Негативное'), (3, 'Компромиссное'), (4, 'Нейтральное'), (5, 'Положительное')], max_length=255, null=True)),
                ('political', models.CharField(blank=True, choices=[(1, 'Коммунистические'), (2, 'Социалистические'), (3, 'Умеренные'), (4, 'Либеральные'), (5, 'Консервативные'), (6, 'Монархические'), (7, 'Ультраконсервативные'), (8, 'Индифферентные'), (9, 'Либертарианские')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_user_id', models.IntegerField()),
                ('avatar', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский'), (0, 'Не указан')], max_length=255, null=True)),
                ('education', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vkusereducation')),
                ('occupation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vkuseroccupation')),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vkuserpersonal')),
            ],
        ),
    ]
