# Generated by Django 3.1.3 on 2020-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuserpersonal',
            name='alcohol',
            field=models.CharField(blank=True, choices=[(0, 'Не указано'), (1, 'Резко негативное'), (2, 'Негативное'), (3, 'Компромиссное'), (4, 'Нейтральное'), (5, 'Положительное')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vkuserpersonal',
            name='political',
            field=models.CharField(blank=True, choices=[(0, 'Не указано'), (1, 'Коммунистические'), (2, 'Социалистические'), (3, 'Умеренные'), (4, 'Либеральные'), (5, 'Консервативные'), (6, 'Монархические'), (7, 'Ультраконсервативные'), (8, 'Индифферентные'), (9, 'Либертарианские')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vkuserpersonal',
            name='smoking',
            field=models.CharField(blank=True, choices=[(0, 'Не указано'), (1, 'Резко негативное'), (2, 'Негативное'), (3, 'Компромиссное'), (4, 'Нейтральное'), (5, 'Положительное')], max_length=255, null=True),
        ),
    ]
