# Generated by Django 3.1.3 on 2020-11-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201129_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuserdata',
            name='education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vkusereducation'),
        ),
        migrations.AlterField(
            model_name='vkuserdata',
            name='occupation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vkuseroccupation'),
        ),
        migrations.AlterField(
            model_name='vkuserdata',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vkuserpersonal'),
        ),
    ]
